FROM node:20-slim AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN corepack enable && yarn install
COPY . .
RUN chmod -R a+x node_modules && yarn build

FROM nginx:alpine AS production
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]